

version: "3"
services:
  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    environment:
      # RABBITMQ_ERLANG_COOKIE: "secret string"
      # RABBITMQ_NODENAME: rabbit1
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      # CLUSTER_NODES: "rabbit@rabbit2,rabbit@rabbit3"
    # volumes:
    #   - "/rabbitmq.config:/etc/rabbitmq/advanced.config"
      # - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    networks:
      - rabbitmq-cluster

  rabbit2:
    image: rabbitmq:3-management
    hostname: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit2
    # volumes:
    #   - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    #   - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "15673:15672"
    # command: >
    #   sh -c "ls &&
    #          sleep 5 &&
    #          rabbitmqctl stop_app &&
    #          sleep 5 &&
    #          rabbitmqctl reset &&
    #          sleep 5 &&
    #          rabbitmqctl join_cluster rabbit@rabbit1 &&
    #          sleep 5 &&
    #          rabbitmqctl start_app"
    # command: sleep 5
    # command: bash -c "sleep 5"
    # command: rabbitmqctl reset
    # # command: sleep 5
    # command: rabbitmqctl join_cluster rabbit@rabbit1
    # # command: sleep 5
    # command: rabbitmqctl start_app
    # command: sleep 5
    networks:
      - rabbitmq-cluster
    # command: sh -c "ls"
    # entrypoint:
    #   - rabbitmqctl stop_app


  rabbit3:
    image: rabbitmq:3-management
    hostname: rabbit3
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: rabbit3
    # volumes:
    #   - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
    #   - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "15674:15672"
    networks:
      - rabbitmq-cluster

networks:
  rabbitmq-cluster:
    driver: bridge