version: '3'
services:
   zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
         ZOOKEEPER_CLIENT_PORT: 2181
         ZOOKEEPER_TICK_TIME: 2000
      ports:
         - "2181:2181"

   kafka:
      image: confluentinc/cp-kafka:latest
      ports:
         - "9092:9092"
      depends_on:
         - zookeeper
      environment:
         KAFKA_BROKER_ID: 1
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         LISTENERS: PLAINTEXT://localhost:9092
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
         KAFKA_NUM_PARTITIONS: 60
         KAFKA_DEFAULT_REPLICATION_FACTOR: 1
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
         ZOOKEEPER_SASL_ENABLED: 'FALSE'
         KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'TRUE'
         # KAFKA_CREATE_TOPICS: "test2:1:1"
         # KAFKA_CREATE_TOPICS: "test2:1:1"
         # KAFKA_CREATE_TOPICS: "test3:1:1"
         #KAFKA_NUM_IO_THREADS: 1 #default value 8
         #KAFKA_NUM_NETWORK_THREADS: 1 #default value 3
         #KAFKA_NUM_REPLICA_FETCHERS: 1 #default value 1