version: '3'
services:
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_IO_THREAD_POOL_SIZE: 1 # default value 128
    ports:
      - "15672:15672"
      - "5672:5672"