version: '3'
services:
   zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
         ZOOKEEPER_CLIENT_PORT: 2181
         ZOOKEEPER_TICK_TIME: 2000
      ports:
         - "2181:2181"

   kafka1:
      image: confluentinc/cp-kafka:latest
      hostname: kafka-1
      ports:
         - "9092:9092"
      depends_on:
         - zookeeper
      environment:
         KAFKA_BROKER_ID: 1
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         LISTENERS: PLAINTEXT://localhost:9092
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:39092,PLAINTEXT_HOST://localhost:9092
         KAFKA_NUM_PARTITIONS: 60
         KAFKA_DEFAULT_REPLICATION_FACTOR: 3
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
         ZOOKEEPER_SASL_ENABLED: 'FALSE'
         KAFKA_CREATE_TOPICS: "test:1:2"
         #help: https://medium.com/@rinu.gour123/kafka-docker-steps-to-run-apache-kafka-using-docker-1645e85acd50

   kafka2:
      image: confluentinc/cp-kafka:latest
      hostname: kafka-2
      ports:
         - "29092:29092"
      depends_on:
         - zookeeper
      environment:
         KAFKA_BROKER_ID: 2
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         LISTENERS: PLAINTEXT://localhost:29092
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:39092,PLAINTEXT_HOST://localhost:29092
         KAFKA_NUM_PARTITIONS: 60
         KAFKA_DEFAULT_REPLICATION_FACTOR: 3
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
         ZOOKEEPER_SASL_ENABLED: 'FALSE'

   kafka3:
      image: confluentinc/cp-kafka:latest
      hostname: kafka-3
      ports:
         - "19092:19092"
      depends_on:
         - zookeeper
      environment:
         KAFKA_BROKER_ID: 3
         KAFKA_ADVERTISED_HOST_NAME: localhost
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         LISTENERS: PLAINTEXT://localhost:19092
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092,PLAINTEXT_HOST://localhost:19092
         KAFKA_NUM_PARTITIONS: 60
         KAFKA_DEFAULT_REPLICATION_FACTOR: 3
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
         KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
         ZOOKEEPER_SASL_ENABLED: 'FALSE'